server:
  # 服务器的HTTP端口
  port: 8088
spring:
  application:
    name: nacos-service-consumer
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 9.135.95.39:8848
# 日志配置
logging:
  level:
    com.demo: debug
    org.springframework: warn