server:
  # 服务器的HTTP端口
  port: 8088
spring:
  application:
    name: consumer-demo
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 127.0.0.1:8848
# 日志配置
logging:
  level:
    com.demo: debug
    org.springframework: warn