server:
  # 服务器的HTTP端口
  port: 8083
spring:
  application:
    name: provider-demo
  cloud:
    nacos:
      username: dev_snail
      password: 5vYwfd6SS1zXXjS
      discovery:
        # 注册中心地址
        server-addr: 10.31.249.218:8848
        namespace: 744f0124-c14b-4ea3-bc22-ce4845c843fd
  profiles:
    include: prometheus

# 日志配置
logging:
  level:
    com.demo: debug
    org.springframework: info