spring:
  cloud:
    nacos:
      username: dev_snail
      password: 5vYwfd6SS1zXXjS
      discovery:
        # 注册中心地址
        server-addr: 10.31.249.218:8848
        namespace: 744f0124-c14b-4ea3-bc22-ce4845c843fd
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000

# 日志配置
logging:
  level:
    com.demo: debug
    org.springframework: info