server:
  # 服务器的HTTP端口
  port: 8081
spring:
  application:
    name: sentinel-demo
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 9.135.95.39:8080 # 指定sentinel控制台地址。
# 日志配置
logging:
  level:
    com.demo: debug
    org.springframework: info