server:
  # 服务器的HTTP端口
  port: 8089
spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: provider-demo
        uri: lb://provider-demo
        predicates:
        - Path=/api/**
        filters:
          - name: Hystrix
            args:
              name: fallbackcmd
              fallbackUri: forward:/hystrix/fallback
# 日志配置
logging:
  level:
    com.demo: debug
    org.springframework: info