server:
  # 服务器的HTTP端口
  port: 8082
spring:
  application:
    name: provider-demo
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 127.0.0.1:8848
#Prometheus springboot监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name} # 暴露的数据中添加application label

# 日志配置
logging:
  level:
    com.demo: debug
    org.springframework: info